<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnidadesEscolaresSeeder extends Seeder
{
    public function run()
    {
        $unidades = [
            'ADOLFINA LEONOR SOARES DOS SANTOS CIEFI PROFª',
            'ADRIANA APARECIDA CASSIANO CEI/EMEI ADI',
            'AIDA DE ALMEIDA CASTRO GRAZIOLI EMEI/EMEF PROFª',
            'ALAOR XAVIER JUNQUEIRA EMEI/EMEF PROF.',
            'ANA MARIA AULICINO CEI PROF.ª',
            'ANTONIA ANTUNES AROUCA EMEF PROFª',
            'ANTONIA RIBEIRO DA SILVA CIEFI PROFª',
            'ANTONIO DE FREITAS AVELAR EMEF PROF.',
            'APARECIDA MARIA PIRES DE MENESES CEI/EMEI PROFª',
            'AURACY MANSANO EMEF PROF.',
            'BENEDITO INÁCIO SOARES EMEI/EMEF',
            'BERNARDO FERREIRA LOUZADA EMEI/EMEF',
            'CARLOS ALTERO ORTEGA EMEI/EMEF',
            'CARLOS DE ALMEIDA RODRIGUES EMEF DR.',
            'CÉLIA ROCHA LOBO CEI/EMEI PROFª',
            'CIASE GOVERNADOR ADHEMAR PEREIRA DE BARROS - TRAVESSÃO',
            'CIASE WILSON FRANCISCO VALENTE - SUMARÉ',
            'DEBORA VALLE DA SILVA PILON EMEF PROFª',
            'EDITH CASTRO DE MORAIS CEI/EMEI PROFª',
            'EDNA MARIA NOGUEIRA FERRAZ CIEFI PROFª',
            'ELISA BUTSCHKAU CEI PROFª',
            'ESTER NUNES DE SOUZA CEI PROFª',
            'EUCLYDES FERREIRA EMEF PROF.',
            'FRANCISCO ASSIS DE CARVALHO CEI/EMEI PROF.',
            'GERALDO DE LIMA EMEF PROF.',
            'HONORINA PACHECO CORRÊA CEI',
            'JANE URBANO FOCESI EMEF PROFª',
            'JOÃO BAPTISTA GARDELIN EMEI/EMEF PROF.',
            'JOÃO BENEDITO MARCONDES EMEI/EMEF PROF.',
            'JOÃO LINO DA CRUZ CEI/EMEI',
            'JOÃO THIMÓTEO DO ROSÁRIO EMEI/EMEF',
            'JORGE PASSOS EMEF PROF.',
            'JOSIANE APARECIDA RAMOS CEI/EMEI PROFª',
            'LEONOR MENDES DE BARROS CEI/EMEI',
            'LÚCIO JACINTO DOS SANTOS EMEI/EMEF PROF.',
            'LUIZ RIBEIRO MUNIZ EMEF PROF.',
            'LUIZ SILVAR DO PRADO EMEF PROF.',
            'MAIRA MARQUES DE OLIVEIRA CEI/EMEI PROFª',
            'MARIA APARECIDA DE CARVALHO EMEF PROFª',
            'MARIA APARECIDA UJIO EMEF PROFª',
            'MARIA CARLITA SARAIVA GUEDES CEI/EMEI PROFª',
            'MARIA DE LOURDES LUCARELLI PEREZ EMEI',
            'MARIA ELMA MANSANO CEI/EMEI PROFª',
            'MARIA EUGENIA ARANHA CHODOUNSKY CEI/EMEI PROFª',
            'MARIA MORAES DE OLIVEIRA EMEF PROFª',
            'MARIA ONICIE DIAS PEREIRA CEI/EMEI PROFª',
            'MARIA THEREZA DE SOUZA CASTRO EMEI/EMEF PROFª',
            'MASAKO SONE EMEI/EMEF',
            'MEI MEI CRECHE - MORRO DO ALGODÃO',
            'MESSIAS MENDES DE SOUZA CEI/EMEI',
            'OSWALDO FERREIRA EMEF PROF.',
            'PEDRO JOÃO DE OLIVEIRA EMEI/EMEF',
            'POIARES - CEI DO BAIRRO',
            'REGINA CÉLIA SANTOS CHAPIRA BLAUSTEIN CEI/EMEI PROFª',
            'RICARDO LUQUES SAMMARCO SERRA EMEFEBS PROF.',
            'SANTINA NARDI MARQUES CEI/EMEI PROFª',
            'SEVERINO VITORIANO DOS SANTOS CEI/EMEI',
            'STELA DA SILVA CEI/EMEI',
            'SUMARÉ CEI/EMEI DO',
            'TELMA DO AMARANTE VEIGA SANTOS CEI',
            'THEREZA YANESSE SCHMIDT CARDOZO CEI/EMEI PROFª',
            'VERA DA SILVA SANTOS CEI/EMEI PROFª',
            'WALDETE FERREIRA DE SOUZA CEI/EMEI INSPETORA',
            'YASUTADA NASU EMEI/EMEF',
            'SECRETARIA MUNICIPAL DE EDUCAÇÃO'
        ];

        foreach ($unidades as $name) {
            DB::table('escolas')->insert(['name' => $name]);
        }
    }
}
